import { savePortfolio } from './fakePortfolioDB'

const dummyPortfolios = [
  {
    userId: 'user_dummy_1',
    profile: {
      userId: 'user_dummy_1',
      name: 'Sarah Chen',
      title: 'Senior Product Designer',
      bio: 'Passionate product designer with 8+ years of experience creating user-centered digital experiences for Fortune 500 companies.',
      avatar: 'https://i.pravatar.cc/150?img=1',
      stats: {
        yearsOfCareer: 8,
        projects: 12,
      },
    },
    coreSkills: ['UI/UX Design', 'Prototyping', 'User Research', 'Design Systems'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'E-commerce Platform Redesign',
        description: 'Led the complete redesign of a major e-commerce platform, improving conversion rates by 35%',
        imageUrl: 'https://placehold.co/600x400/4F46E5/FFFFFF/png?text=E-commerce+Platform',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2020',
        title: 'Senior Product Designer',
        company: 'Google',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['Figma', 'Sketch', 'Adobe XD'],
    portfolioLayouts: [],
  },
  {
    userId: 'user_dummy_2',
    profile: {
      userId: 'user_dummy_2',
      name: 'Marcus Rodriguez',
      title: 'Full Stack Developer',
      bio: 'Full-stack developer specializing in React, Node.js, and cloud architecture. Passionate about building scalable web applications.',
      avatar: 'https://i.pravatar.cc/150?img=12',
      stats: {
        yearsOfCareer: 6,
        projects: 18,
      },
    },
    coreSkills: ['React', 'Node.js', 'AWS', 'TypeScript'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'Microservices Architecture',
        description: 'Architected and implemented microservices infrastructure serving 1M+ users',
        imageUrl: 'https://placehold.co/600x400/10B981/FFFFFF/png?text=Microservices',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2019',
        title: 'Full Stack Developer',
        company: 'Microsoft',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['Docker', 'Kubernetes', 'GraphQL'],
    portfolioLayouts: [],
  },
  {
    userId: 'user_dummy_3',
    profile: {
      userId: 'user_dummy_3',
      name: 'Emily Watson',
      title: 'Marketing Director',
      bio: 'Strategic marketing leader with expertise in digital campaigns, brand management, and growth marketing for B2B SaaS companies.',
      avatar: 'https://i.pravatar.cc/150?img=5',
      stats: {
        yearsOfCareer: 10,
        projects: 15,
      },
    },
    coreSkills: ['Digital Marketing', 'Brand Strategy', 'Analytics', 'Growth Hacking'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'Brand Repositioning Campaign',
        description: 'Led brand repositioning that resulted in 50% increase in market awareness',
        imageUrl: 'https://placehold.co/600x400/EC4899/FFFFFF/png?text=Brand+Campaign',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2015',
        title: 'Marketing Director',
        company: 'Meta',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['SEO', 'Content Marketing', 'Marketing Automation'],
    portfolioLayouts: [],
  },
  {
    userId: 'user_dummy_4',
    profile: {
      userId: 'user_dummy_4',
      name: 'David Kim',
      title: 'Data Scientist',
      bio: 'Data scientist with expertise in machine learning, predictive analytics, and AI model development for enterprise solutions.',
      avatar: 'https://i.pravatar.cc/150?img=13',
      stats: {
        yearsOfCareer: 7,
        projects: 22,
      },
    },
    coreSkills: ['Python', 'Machine Learning', 'SQL', 'TensorFlow'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'Predictive Analytics Model',
        description: 'Developed ML model that improved prediction accuracy by 40%',
        imageUrl: 'https://placehold.co/600x400/F59E0B/FFFFFF/png?text=ML+Analytics',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2018',
        title: 'Data Scientist',
        company: 'Amazon',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['PyTorch', 'Pandas', 'Data Visualization'],
    portfolioLayouts: [],
  },
  {
    userId: 'user_dummy_5',
    profile: {
      userId: 'user_dummy_5',
      name: 'Jessica Thompson',
      title: 'Brand Designer',
      bio: 'Creative brand designer specializing in visual identity, logo design, and brand strategy for startups and established brands.',
      avatar: 'https://i.pravatar.cc/150?img=9',
      stats: {
        yearsOfCareer: 9,
        projects: 28,
      },
    },
    coreSkills: ['Brand Identity', 'Logo Design', 'Adobe Creative Suite', 'Typography'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'Startup Brand Identity',
        description: 'Created complete brand identity for 5 successful startups',
        imageUrl: 'https://placehold.co/600x400/EF4444/FFFFFF/png?text=Brand+Identity',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2016',
        title: 'Brand Designer',
        company: 'Adobe',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['Illustration', 'Motion Graphics', 'Brand Guidelines'],
    portfolioLayouts: [],
  },
  {
    userId: 'user_dummy_6',
    profile: {
      userId: 'user_dummy_6',
      name: 'Alex Johnson',
      title: 'Product Manager',
      bio: 'Strategic product manager with a track record of launching successful digital products and driving user growth at scale.',
      avatar: 'https://i.pravatar.cc/150?img=14',
      stats: {
        yearsOfCareer: 8,
        projects: 16,
      },
    },
    coreSkills: ['Product Strategy', 'Roadmapping', 'Analytics', 'Agile'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'Product Launch Strategy',
        description: 'Successfully launched 5 products reaching 500K+ users in first year',
        imageUrl: 'https://placehold.co/600x400/8B5CF6/FFFFFF/png?text=Product+Launch',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2017',
        title: 'Product Manager',
        company: 'Spotify',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['Product Analytics', 'User Stories', 'A/B Testing'],
    portfolioLayouts: [],
  },
  {
    userId: 'user_dummy_7',
    profile: {
      userId: 'user_dummy_7',
      name: 'Rachel Green',
      title: 'UX Researcher',
      bio: 'UX researcher passionate about understanding user behavior and translating insights into actionable design recommendations.',
      avatar: 'https://i.pravatar.cc/150?img=10',
      stats: {
        yearsOfCareer: 5,
        projects: 14,
      },
    },
    coreSkills: ['User Research', 'Usability Testing', 'Data Analysis', 'Journey Mapping'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'User Research Initiative',
        description: 'Conducted comprehensive user research improving product satisfaction by 45%',
        imageUrl: 'https://placehold.co/600x400/06B6D4/FFFFFF/png?text=UX+Research',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2020',
        title: 'UX Researcher',
        company: 'Airbnb',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['Qualitative Research', 'Quantitative Analysis', 'Persona Development'],
    portfolioLayouts: [],
  },
  {
    userId: 'user_dummy_8',
    profile: {
      userId: 'user_dummy_8',
      name: 'Michael Chang',
      title: 'Frontend Developer',
      bio: 'Frontend developer specializing in creating beautiful, responsive web applications with modern JavaScript frameworks.',
      avatar: 'https://i.pravatar.cc/150?img=15',
      stats: {
        yearsOfCareer: 6,
        projects: 20,
      },
    },
    coreSkills: ['JavaScript', 'React', 'Vue.js', 'CSS Animation'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'Component Library',
        description: 'Built reusable component library adopted by 50+ projects',
        imageUrl: 'https://placehold.co/600x400/14B8A6/FFFFFF/png?text=Component+Library',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2019',
        title: 'Frontend Developer',
        company: 'Shopify',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['Next.js', 'Tailwind CSS', 'Performance Optimization'],
    portfolioLayouts: [],
  },
  {
    userId: 'user_dummy_9',
    profile: {
      userId: 'user_dummy_9',
      name: 'Sophia Martinez',
      title: 'Content Strategist',
      bio: 'Content strategist focused on creating compelling narratives that drive engagement and build strong brand connections.',
      avatar: 'https://i.pravatar.cc/150?img=20',
      stats: {
        yearsOfCareer: 7,
        projects: 18,
      },
    },
    coreSkills: ['Content Strategy', 'Copywriting', 'SEO', 'Social Media'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'Content Marketing Strategy',
        description: 'Developed content strategy increasing organic traffic by 200%',
        imageUrl: 'https://placehold.co/600x400/F472B6/FFFFFF/png?text=Content+Strategy',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2018',
        title: 'Content Strategist',
        company: 'Instagram',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['Content Planning', 'Editorial Calendar', 'Brand Voice'],
    portfolioLayouts: [],
  },
  {
    userId: 'user_dummy_10',
    profile: {
      userId: 'user_dummy_10',
      name: 'James Wilson',
      title: 'DevOps Engineer',
      bio: 'DevOps engineer with expertise in cloud infrastructure, automation, and building scalable deployment pipelines.',
      avatar: 'https://i.pravatar.cc/150?img=33',
      stats: {
        yearsOfCareer: 8,
        projects: 25,
      },
    },
    coreSkills: ['AWS', 'Docker', 'Kubernetes', 'CI/CD'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'Cloud Infrastructure',
        description: 'Automated deployment reducing release time by 80%',
        imageUrl: 'https://placehold.co/600x400/F59E0B/FFFFFF/png?text=Cloud+Infrastructure',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2017',
        title: 'DevOps Engineer',
        company: 'AWS',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['Terraform', 'Jenkins', 'Monitoring'],
    portfolioLayouts: [],
  },
  {
    userId: 'user_dummy_11',
    profile: {
      userId: 'user_dummy_11',
      name: 'Lisa Anderson',
      title: 'Graphic Designer',
      bio: 'Graphic designer with a passion for creating visually stunning designs across print and digital mediums.',
      avatar: 'https://i.pravatar.cc/150?img=23',
      stats: {
        yearsOfCareer: 9,
        projects: 31,
      },
    },
    coreSkills: ['Graphic Design', 'Print Design', 'Illustration', 'Branding'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'Visual Design Portfolio',
        description: 'Created award-winning designs for 20+ international brands',
        imageUrl: 'https://placehold.co/600x400/3B82F6/FFFFFF/png?text=Graphic+Design',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2016',
        title: 'Graphic Designer',
        company: 'Behance',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['Adobe Illustrator', 'Photoshop', 'InDesign'],
    portfolioLayouts: [],
  },
  {
    userId: 'user_dummy_12',
    profile: {
      userId: 'user_dummy_12',
      name: 'Robert Taylor',
      title: 'Mobile App Developer',
      bio: 'Mobile app developer specializing in native iOS and Android applications with focus on user experience and performance.',
      avatar: 'https://i.pravatar.cc/150?img=52',
      stats: {
        yearsOfCareer: 6,
        projects: 17,
      },
    },
    coreSkills: ['Swift', 'Kotlin', 'React Native', 'Flutter'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'Mobile App Suite',
        description: 'Developed mobile apps with 2M+ downloads and 4.8 star rating',
        imageUrl: 'https://placehold.co/600x400/6366F1/FFFFFF/png?text=Mobile+Apps',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2019',
        title: 'Mobile App Developer',
        company: 'Apple',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['iOS Development', 'Android Development', 'Mobile UI'],
    portfolioLayouts: [],
  },
  {
    userId: 'user_dummy_13',
    profile: {
      userId: 'user_dummy_13',
      name: 'Amanda Foster',
      title: 'Digital Marketing Manager',
      bio: 'Digital marketing manager with expertise in paid advertising, social media campaigns, and conversion optimization.',
      avatar: 'https://i.pravatar.cc/150?img=44',
      stats: {
        yearsOfCareer: 7,
        projects: 19,
      },
    },
    coreSkills: ['PPC', 'Social Media', 'Google Analytics', 'Email Marketing'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'Digital Campaign Success',
        description: 'Managed campaigns generating $5M+ in revenue with 300% ROI',
        imageUrl: 'https://placehold.co/600x400/10B981/FFFFFF/png?text=Digital+Marketing',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2018',
        title: 'Digital Marketing Manager',
        company: 'Google',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['Facebook Ads', 'Google Ads', 'Marketing Automation'],
    portfolioLayouts: [],
  },
  {
    userId: 'user_dummy_14',
    profile: {
      userId: 'user_dummy_14',
      name: 'Kevin Lee',
      title: 'Backend Developer',
      bio: 'Backend developer focused on building robust, scalable server-side applications and API integrations.',
      avatar: 'https://i.pravatar.cc/150?img=59',
      stats: {
        yearsOfCareer: 8,
        projects: 21,
      },
    },
    coreSkills: ['Java', 'Spring Boot', 'PostgreSQL', 'Microservices'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'API Platform',
        description: 'Built API platform handling 10M+ requests daily',
        imageUrl: 'https://placehold.co/600x400/8B5CF6/FFFFFF/png?text=Backend+API',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2017',
        title: 'Backend Developer',
        company: 'Microsoft',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['REST APIs', 'GraphQL', 'Database Design'],
    portfolioLayouts: [],
  },
  {
    userId: 'user_dummy_15',
    profile: {
      userId: 'user_dummy_15',
      name: 'Nicole Brooks',
      title: 'UI Designer',
      bio: 'UI designer passionate about creating intuitive and visually appealing user interfaces for web and mobile applications.',
      avatar: 'https://i.pravatar.cc/150?img=47',
      stats: {
        yearsOfCareer: 6,
        projects: 24,
      },
    },
    coreSkills: ['UI Design', 'Figma', 'Design Systems', 'Prototyping'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'Design System',
        description: 'Created comprehensive design system used across 30+ products',
        imageUrl: 'https://placehold.co/600x400/EC4899/FFFFFF/png?text=UI+Design+System',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2019',
        title: 'UI Designer',
        company: 'Sketch',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['Responsive Design', 'Interaction Design', 'Visual Design'],
    portfolioLayouts: [],
  },
  {
    userId: 'user_dummy_16',
    profile: {
      userId: 'user_dummy_16',
      name: 'Daniel Garcia',
      title: 'Business Analyst',
      bio: 'Business analyst specializing in requirements gathering, process optimization, and stakeholder communication.',
      avatar: 'https://i.pravatar.cc/150?img=68',
      stats: {
        yearsOfCareer: 5,
        projects: 13,
      },
    },
    coreSkills: ['Requirements Analysis', 'Process Mapping', 'Stakeholder Management', 'Documentation'],
    featuredProjects: [
      {
        id: 'proj-1',
        title: 'Process Optimization',
        description: 'Optimized business processes saving $2M+ annually',
        imageUrl: 'https://placehold.co/600x400/0EA5E9/FFFFFF/png?text=Business+Analysis',
        technologies: [],
        link: '',
        status: 'completed' as const,
      },
    ],
    careerTimeline: [
      {
        id: 'career-1',
        year: '2020',
        title: 'Business Analyst',
        company: 'Slack',
      },
    ],
    achievementBadges: [],
    performanceMetrics: [],
    feedPosts: [],
    uploadedFiles: [],
    suggestedSkills: ['Business Intelligence', 'Data Modeling', 'Agile Methodology'],
    portfolioLayouts: [],
  },
]

export async function seedDummyPortfolios() {
  console.log('Seeding dummy portfolios...')

  for (const portfolio of dummyPortfolios) {
    await savePortfolio(portfolio.userId, portfolio as any)
  }

  console.log(`Seeded ${dummyPortfolios.length} dummy portfolios`)
}
